---
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release & Publish PatternFly Fritz2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew dokkaHtml
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/dokka/html
          CLEAN: true
      - run: ./gradlew build
      - uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            build/libs/patternfly-fritz2*.jar
      - run: ./gradlew build publish generatePomFileForMavenPublication bintrayUpload
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_ORG: ${{ secrets.BINTRAY_ORG }}
